---
##########################
## Mailman installation ##
##########################

- name: "Mailman | Debconf for mailman"
  debconf:
    name: mailman
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { question: 'mailman/used_languages', value: 'en', vtype: 'multiselect' }
    - { question: 'mailman/create_site_list', value: '', vtype: 'multiselect' }

- name: "Mailman | Install package"
  apt:
    name: "{{ item }}"
  register: mailman_package_install
  with_items:
    - mailman

- name: "Mailman | Generate random password for admin_email"
  set_fact:
    admin_email_mailman_password: "{{ lookup('password', '/tmp/passwordfile chars=ascii_letters,digits') }}"
  when:
    - admin_email_mailman_password is not defined
  no_log: true

- name: "Mailman | Configure new maillist"
  command: echo {{ admin_email }} | echo {{ admin_email_mailman_password }} | newlist mailman
  register: mailman_new_maillist
  when: mailman_package_install.changed

- name: "Mailman | Configure /etc/aliases"
  template:
    src: "04-mailman.{{ item }}"
    dest: "/etc/{{ item }}"
  with_items:
    - aliases

- name: "Mailman | Symlink"
  file:
    src: /etc/mailman/apache.conf
    dest: /etc/apache2/conf-enabled/mailman.conf
    state: link
  when: not ansible_check_mode

- name: "Mailman | Ensure /var/lib/mailman/aliases exist"
  file:
    path: /var/lib/mailman/data/aliases
    state: touch
  when: mailman_package_install.changed

- name: "Mailman | newaliases"
  shell: newaliases
  when: mailman_new_maillist.changed

- name: "Mailman | Add mailman=yes to /etc/facts.conf"
  lineinfile:
    path: /etc/facts.conf
    line: 'mailman=yes'
