---
- name: "Hostname | Configure /etc/hosts"
  lineinfile:
    path: /etc/hosts
    state: present
    line: '{{ ip_smtp }} {{ hostname_fqdn }} {{ hostname }} '
   when: ip_smtp is defined AND hostname_fqdn is defined AND hostname is defined

- name: "Hostname | Configure /etc/hostname"
  hostname:
    name: '{{ hostname) }}'
  when: hostname is defined
