---
- name: "ISPConfig-Installer | Download"
  get_url:
    url: http://www.ispconfig.org/downloads/ISPConfig-3-stable.tar.gz
    dest: /tmp/ISPConfig-3-stable.tar.gz

- name: "ISPConfig-Installer | Unarchive"
  unarchive:
    src: /tmp/ISPConfig-3-stable.tar.gz
    dest: /tmp/
    remote_src: yes
  when: not ansible_check_mode
