---
# https://www.howtoforge.com/tutorial/securing-ispconfig-3-with-a-free-lets-encrypt-ssl-certificate/

- name: "ISPConfig-SSL | Backup old certificate"
  shell: cd /usr/local/ispconfig/interface/ssl/ && mv ispserver.crt ispserver.crt-$(date +"%y%m%d%H%M%S").bak && mv ispserver.key ispserver.key-$(date +"%y%m%d%H%M%S").bak

- name: "ISPConfig-SSL | Put symlink of the LE SSL to ispconfig location 1/2"
  file:
    src: '/etc/letsencrypt/live/{{ hostname_fqdn }}/fullchain.pem'
    dest: '/usr/local/ispconfig/interface/ssl/ispserver.crt'
    state: link

- name: "ISPConfig-SSL | Put symlink of the LE SSL to ispconfig location 2/2"
  file:
    src: '/etc/letsencrypt/live/{{ hostname_fqdn }}/privkey.pem'
    dest: '/usr/local/ispconfig/interface/ssl/ispserver.key'
    state: link

- name: "ISPConfig-SSL | Assemble ispserver.pem"
  shell: cat /usr/local/ispconfig/interface/ssl/ispserver.{key,crt} > /usr/local/ispconfig/interface/ssl/ispserver.pem

- name: "ISPConfig-SSL | chmod 600 LE SSL"                                                                                                                                                    
  file:                                                                                                                                                                                                          
    path: /usr/local/ispconfig/interface/ssl/ispserver.pem
    mode: 0600                                                                                                                                                                                                   

- name: "ISPConfig-SSL | Backup old certificate for postfix"
  shell: cd /etc/postfix/ && mv smtpd.cert smtpd.cert-$(date +"%y%m%d%H%M%S").bak && mv smtpd.key smtpd.key-$(date +"%y%m%d%H%M%S").bak

- name: "ISPConfig-SSL | Put symlink of the LE SSL to postfix location 1/2"
  file:
    src: '/usr/local/ispconfig/interface/ssl/ispserver.key'
    dest: '/etc/postfix/smtpd.key'
    state: link

- name: "ISPConfig-SSL | Put symlink of the LE SSL to postfix location 2/2"
  file:
    src: '/usr/local/ispconfig/interface/ssl/ispserver.crt'
    dest: '/etc/postfix/smtpd.cert'
    state: link

- name: "ISPConfig-SSL | Put symlink of the LE SSL to pure-ftpd ssl location"
  file:
    src: '/usr/local/ispconfig/interface/ssl/ispserver.pem'
    dest: '/etc/ssl/private/pure-ftpd.pem'
    state: link

- name: "ISPConfig-SSL | chmod 600 LE SSL"
  file:
    path: /etc/ssl/private/pure-ftpd.pem
    mode: 0600                                                                                                                                                                                                   

- name: "ISPConfig-SSL | Setup ssl cert for dovecot 1/2"
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    regexp: 'ssl_cert$'
    line: 'ssl_cert = </etc/postfix/smtpd.cert'

- name: "ISPConfig-SSL | Setup ssl cert for dovecot 2/2"
  lineinfile:
    path: /etc/dovecot/dovecot.conf
    regexp: 'ssl_key$'
    line: 'ssl_key = </etc/postfix/smtpd.key'

- name: "ISPConfig-SSL | Set template file in /etc/init.d/le_ispc_pem.sh"
  template:
    src:  le_ispc_pem.sh
    dest: /etc/init.d/le_ispc_pem.sh
    mode: 0750

- name: "ISPConfig-SSL | Setup Incron job"
  shell: echo "/etc/letsencrypt/archive/$(hostname -f)/ IN_MODIFY ./etc/init.d/le_ispc_pem.sh" >> /var/spool/incron/root
