---
- name: "Postfix | Configure /etc/postfix/master.cf"
  template:
    src: "postfix.{{ item }}"
    dest: "/etc/postfix/{{ item }}"
    mode: 0444
  with_items:
    - main.cf
    - master.cf
    - transport_slow
