#!/bin/bash
# Check presence socket

# check variables

if [[ -z $1 || -z $2 ]];then
        echo "Usage: ./check_dspam_socket <Path> <Filename>"
        exit 1
fi

if [[ $(find $1 -type s -name $2) ]]; then
        echo 1
else
        echo 0
fi
