#!/bin/bash

file='/etc/fstab'
DEVF=''
MOUNTF=''
EXIT_ID='0'

for dev in $(cat $file | grep "^/" | grep -v "//" | awk '{print $1}' ) ; do
        if [ ! -e $dev ] ; then
                DEVF=${DEVF}" $dev"
        fi
done

for mount in $(cat $file | grep "^/" | grep -v "^/dev/scd\|^/dev/sr" | grep -v "^/dev/sr" | awk '{print $2}' | sed 's:/$::' ) ; do
        [[ $mount = 'none' ]] && continue
        if [ $(mount | grep "on $mount " | wc -m) -le 1 ] ; then
                MOUNTF=${MOUNTF}" $mount"
        fi
done

for nfs in $(cat $file | grep " nfs " | grep -v "^#" | awk '{print $2}' | sed 's:/$::' ) ; do
        [[ $nfs = 'none' ]] && continue
        if [ $(mount | grep "on $nfs " | wc -m) -le 1 ] ; then
                MOUNTF=${MOUNTF}" $nfs"
        fi
done

if ( [ $(echo $DEVF | wc -m ) -gt 1 ] || [ $(echo $MOUNTF | wc -m ) -gt 1 ] ) ; then
        echo "Failed on $DEVF $MOUNTF"
        exit 2
fi

echo "fstab ok"
exit 0